name: "Event Store"
description: "The open-source, functional database with Complex Event Processing in JavaScript."
url: "https://eventstore.org"
permalink: /blog/:year:month:day/:title/index.html
sass:
    sass_dir: _sass
    style: compressed